###
POST http://localhost:3333/account
Content-Type: application/json

{
     "uname": "name",
    "umobile" : "mobile",
    "uemail" : "email",
    "upassword" : "password" ,
    "ugender" :  "gender",
    "ucity" : "city",
    "ustate" : "keyword",
    "usource" : "source"
}

//spacing matter

###
POST http://localhost:3333/adduser
Content-Type: application/json

{
     "name": "aryan",
    "mobile" : "876786887",
    "email" : "aryan@gmail.com",
    "date": "1/6/2024, 9:52:47 PM"
}

###
GET http://localhost:3333/retrieveuser



###
GET http://localhost:3333/user/6596a477e40001cbabc37c3b


###
PUT http://localhost:3333/edituser
Content-Type: application/json

{
   "fullname": "Mohit",
   "salary": 988998,
   "department": "Director of Board",
   "cityname": "Patna",
   "id": "65870e43bcc85808802d3451"
}


###
DELETE http://localhost:3333/deleteuser/659a1aa6a61c9d6813000b55